### ISSUE TITLE
Minimum word length

### ISSUE THREAD

**Issue by lindahovila** [msaari/relevanssi-live-ajax-search#10]
Hello,

Is there a way to change the minimum word length? I would like to make search results come up when the search word is at length of 2. I have already lowered the minimum length in Relevanssi to 2, but it does not seem to have effect on Live Ajax Search. 

Thanks

**Comment by msaari** [comment]
Yes, you can modify the configs:

`add_filter( 'relevanssi_live_search_configs', function( $config ) {
  $config['default']['input']['min_chars'] = 2;
  return $config;
} );`
