### ISSUE TITLE
Conflicts with Envato Market Plugin and Breaks all plugin updates

### ISSUE THREAD

**Issue by MACscr** [msaari/relevanssi-live-ajax-search#13]
Ive toggled the activation of the two plugins to confirm, but when both plugins are enabled, wordpress plugin updates fail with the following error on WP 6.0.1 with php 7.4:

> AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Relevanssi_Live_Search_Client::control_active_plugins() must be of the type array, bool given, called in /var/www/staging/wp-includes/class-wp-hook.php on line 309 and defined in /var/www/staging/wp-content/plugins/relevanssi-live-ajax-search/includes/class-relevanssi-live-search-client.php:47\nStack trace:\n#0 /var/www/staging/wp-includes/class-wp-hook.php(309): Relevanssi_Live_Search_Client->control_active_plugins()\n#1 /var/www/staging/wp-includes/plugin.php(191): WP_Hook->apply_filters()\n#2 /var/www/staging/wp-includes/option.php(1488): apply_filters()\n#3 /var/www/staging/wp-includes/option.php(1307): get_network_option()\n#4 /var/www/staging/wp-content/plugins/envato-market/inc/class-envato-market-github.php(231): get_site_option()\n#5 /var/www/staging/wp-content/plugins/envato-market/inc/class-envato-market-github.php(264): Envato_Market_Github->state()\n#6 /var/www/staging/wp-includes/class-wp-hook.php(309): Envato_Market_Git...', referer: https://staging.example.com/wp-admin/plugins.php

**Comment by msaari** [comment]
This is related to a feature I've already removed from the plugin in the development; it will be gone in the next version once I release it (in August, likely). To get rid of this problem, you can edit the file `/includes/class-relevanssi-live-search-client.php` in Relevanssi Live Ajax Search and remove these lines:

`add_filter( 'option_active_plugins', array( $this, 'control_active_plugins' ) );
add_filter( 'site_option_active_sitewide_plugins', array( $this, 'control_active_plugins' ) );`

Might be worth noting Envato Market Plugin about this, too. That filter should always get an array, and if Envato Market Plugin is returning a boolean there, this plugin isn't the only thing that will break.
