### ISSUE TITLE
How to speed up Relevanssi ajax live search results?

### ISSUE THREAD

**Issue by stratboy** [msaari/relevanssi-live-ajax-search#3]
Hi, thank you for your code.

I tried Relevanssi 'standard' with the live ajax search, but results are wuite slow to come out (with very very little posts currently saved). So how to speed up Relevanssi 'standard' + ajax live search? :)

Currently on wp 5.9.0, php 8.0.8, mysql 5.7.34. 
Basic local installation, just inited with few posts (custom post type: product with some taxonomy terms). Currently all very basic. 

Regards

**Comment by msaari** [comment]
The first question is: what do you mean with slow exactly? Second, five seconds, ten seconds, a minute? It's normal for Relevanssi requests to take a second or two; if you need millisecond response times, Relevanssi is not the tool for you.

The second question is: what is taking the time? If you run a standard Relevanssi query, how long does that take? Query Monitor is a good tool for that, it'll show you how many seconds the query took, and it'll show you how long each database query takes.

You can also analyze the request to see if your server takes time to respond to the request.

Once you know where the time goes, it's easier to figure out how to make things faster.

One trick you can try is this:

```
add_filter( 'relevanssi_live_search_query_args', function( $args ) {
  add_filter( 'relevanssi_excerpt_post', '__return_false' );
  return $args;
} );
```

This will disable Relevanssi excerpts from the AJAX search. Creating the excerpts is a big part of the search and sometimes takes longer than the actual searching, and if you're not using the excerpts, why waste time creating them?

**Comment by stratboy** [comment]
Hi, thank you. First question: 2-3 seconds with spinner, then results appear.

Secondo question: I think I'm not too good in using query monitor, don't think I'm using it correctly. Results don't seem to be relevant. Attaching something. Query from relevanssi is said to be only from vz_options, and I guess it's not... Also I got some errors in console when using live search. Finally, query monitor complains about no having redis and the like. I'll have them. aving redis will make relevanssi faster?

Finally, using that filter doesn't speed up anything.

<img width="1400" alt="Schermata 2022-02-02 alle 09 26 01" src="https://user-images.githubusercontent.com/437598/152119452-71f9ddf9-3d65-475c-9152-77165010dcec.png">
<img width="1190" alt="Schermata 2022-02-02 alle 09 32 31" src="https://user-images.githubusercontent.com/437598/152119406-0a613f95-8f02-4d9f-ac2e-9e8a2d832fb7.png">
<img width="857" alt="Schermata 2022-02-02 alle 09 24 30" src="https://user-images.githubusercontent.com/437598/152119435-889f09f3-7dc1-4250-b778-0d4f3ce64d89.png">

**Comment by msaari** [comment]
Ok, 2-3 seconds is fairly normal for Relevanssi. I don't think you can expect to make it much faster than that. If you want truly instant results, Relevanssi won't be able to deliver that. Some improvement may be possible.

I don't think Redis is going to help much with Relevanssi, except in the cases where the same searches are done a lot.

Query Monitor won't help you with the AJAX queries, it can't catch them. [You can use Query Monitor to check the regular Relevanssi queries](https://www.relevanssi.com/knowledge-base/debugging-with-query-monitor/), which will provide more information for AJAX queries too, because that Relevanssi query is what the AJAX query is doing behind the scenes.

If the function does nothing, you can also try disabling excerpt creation from Relevanssi settings to see if that helps. But it's possible it simply doesn't have much effect at all if generating excerpts for your posts is easy.

**Comment by stratboy** [comment]
Great, thank you. One last thing: how about the strange console error I'm getting with ajax live search? Do you think it's coming straight from the plugin or is it something from my theme?

**Comment by stratboy** [comment]
> Great, thank you. One last thing: how about the strange console error I'm getting with ajax live search? Do you think it's coming straight from the plugin or is it something from my theme?

No, excuse me: I just realised it's there only when query monitor is active...

**Comment by msaari** [comment]
The one in the screenshot? The file reference points to Query Monitor, but without seeing the whole thing and the whole stack, it's hard to say what's up with that. In any case, it's referencing things Relevanssi Live Ajax Search doesn't do.

**Comment by stratboy** [comment]
> The one in the screenshot? The file reference points to Query Monitor, but without seeing the whole thing and the whole stack, it's hard to say what's up with that. In any case, it's referencing things Relevanssi Live Ajax Search doesn't do.

Yes, thank you. Going to close the thread. Regards.
