### ISSUE TITLE
Change number of results shown

### ISSUE THREAD

**Issue by iangeek** [msaari/relevanssi-live-ajax-search#4]
Hi,

Sorry if this is a basic one, but how can I change the number of results returned live?  Currently its defaulting to 7. 

Great work though

**Comment by msaari** [comment]
You can use the `relevanssi_live_search_posts_per_page` filter hook to adjust the value:

`add_filter( 'relevanssi_live_search_posts_per_page', function() { return 10; } );`

**Comment by iangeek** [comment]
Thanks for your help Mikko
