### ISSUE TITLE
Compatibility with Search and Filter Pro plugin

### ISSUE THREAD

**Issue by guyaldous1** [msaari/relevanssi-live-ajax-search#5]
Hi there,

Just a query as to the compatibility of this plugin with the search and filter pro plugin? I know that the basic relevanssi package works but could the also be added to a search field?

Thanks

**Comment by msaari** [comment]
I don't have access to Search & Filter Pro, so I can't give it a go. I tried the free version, and it does such a custom job with the search form that Relevanssi Live Ajax Search can't take it over automatically. The free version doesn't have filter hooks that could be used to fix that, so you'd have to edit the shortcode output manually to add in the Live Ajax Search code. So I'd say it's possible but quite clumsy.

The Pro version also customizes the search form enough to make it incompatible with Live Ajax Search. Also, Search & Filter Pro seems to have a live search feature of its own, based on the demo on their site, so it's probably just best to use that.

If you don't want to use the live search in Search & Filter Pro and there's some way to add extra parameters to the search form fields, then yes, Relevanssi Live Ajax Search can be used with Search & Filter Pro.
