### ISSUE TITLE
Plugin doesn't seem to be working at all

### ISSUE THREAD

**Issue by ScottNasher** [msaari/relevanssi-live-ajax-search#6]
After installing and trying searches on the /?s= page, I don't seem to see any ajax taking effect. I've tried with both relevanssi premium enabled and disabled for default WP search.

I also tried to copy the search-results.php into /relevanssi-live-ajax-search in my active child theme and add an H1 to test, but the template doesn't seem to be taking affect at all.

Maybe I missed a step in the installation process? I've tried both 1.0.0 and 1.1.0

**Comment by msaari** [comment]
There are no installation steps required generally, but if your theme is using a search form that is unusual enough, Relevanssi Live Ajax Search won't be able to latch on to it.

If you look at your search form, the `input` field for the search terms should have `data-rlvlive="true"` and `data-rlvconfig="default"` parameters in it. Does it?

If it doesn't, the plugin hasn't been able to hook on to your search form. The plugin uses `get_search_form` and `render_block` hooks to try to do that, but if your search form is not using these hooks, then of course nothing will happen. In that case, you need to manually edit your form to add the parameters to the form.

If it does have the parameters, the plugin has successfully connected to your search form. If the search still does not work, then check the Javascript console for errors. There should be a `<script>` tag with the id `relevanssi-live-search-client` on the page. Is there? Perhaps the Javascript is missing for some reason. Relevanssi Live Ajax Search requires jQuery, so if the default jQuery library has been removed or renamed, the search will not work.

**Comment by Dioqa** [comment]
Hello

I have the same problem. I added the module, I checked the different parameters are taken into account. 

I see a 404 error in the console. The site is in beta and is only in HTTP, can the error come from the fact that the site is not secure? 

Thanks in advance.
Pierre

**Comment by msaari** [comment]
Which file is causing the 404 error? The Live Ajax Search JS file? Can you please show me the 404 error? The plugin doesn't care about HTTP vs HTTPS, that should not be a problem.

**Comment by Dioqa** [comment]
Thanks for your reactivity,

Here is the screenshot of the error in the console. 

I hope that it is convenient for you? 

Thanks in advance
![Capture-dimos](https://user-images.githubusercontent.com/100369283/155572156-0de07225-1de3-462e-bba0-f3f5a0f0897c.PNG)

**Comment by msaari** [comment]
The server AJAX URL parameter is set to `/ajax`, and that does not exist. It should be `admin_url( 'admin-ajax.php' )`, ie. the `admin-ajax.php` file in `wp-admin/admin-ajax.php`. Do you know why that would be so? That's why the search is not working, it's looking for the `admin-ajax.php` in the wrong place.

**Comment by Dioqa** [comment]
Hello,

Thank you for your feedback and help. The problem is solved. 
The old provider had changed the ajax URL.

Thank you for your reactivity.
Pierre
