### ISSUE TITLE
Alter query

### ISSUE THREAD

**Issue by jimmywags** [msaari/relevanssi-live-ajax-search#8]
I'm trying to change the order (and group) the results of the search results. I tried hooking into the _relevanssi_live_search_query_args_ filter, but my results are not changing.

I tried this:
`add_filter('relevanssi_live_search_query_args', 'ld_alter_search_query_args');

function ld_alter_search_query_args( $query_args ){
  $query_args['post_type'] = array( 'events', 'page');
  $query_args['orderby'] = array( 'type', 'name' );
  return $query_args;
}`

Thoughts?

**Comment by msaari** [comment]
This seems to work fine when I tested this. I did change the `orderby` to include the direction, I think that is mandatory when using the array syntax:

`$query_args['orderby'] = array( 'type' => 'asc', 'name' => 'asc' );`

But other than that, I see no reason why this wouldn't work.

**Comment by jimmywags** [comment]
Yes. You are right. Adding the direction to the orderby cleared it up. Thank you for the wonderful plugin.
